"use client"
import {Exam} from '../../types/quiz';


export const exams: Exam[] = [
    {
        id: '1',
        title: 'EE.08 2018 czerwiec',
        description: 'Egzamin praktyczny EE.08',
        year: 2018,
        session: 'Summer',
        category: 'EE 0.8',
        downloadUrl: '#',
      },
      {
        id: '2',
        title: 'EE.08 2019 czerwiec',
        description: 'Egzamin praktyczny EE.08',
        year: 2019,
        session: 'Summer',
        category: 'EE 0.8',
        downloadUrl: '#',
      },
      {
        id: '3',
        title: 'EE.08 2019 styczeń',
        description: 'Egzamin praktyczny EE.08',
        year: 2019,
        session: 'Winter',
        category: 'EE 0.8',
        downloadUrl: '#',
      },
      {
        id: '4',
        title: 'EE.08 2020 czerwiec',
        description: 'Egzamin praktyczny EE.08',
        year: 2020,
        session: 'Summer',
        category: 'EE 0.8',
        downloadUrl: '#',
      },
      {
        id: '5',
        title: 'EE.08 2020 styczeń',
        description: 'Egzamin praktyczny EE.08',
        year: 2020,
        session: 'Winter',
        category: 'EE 0.8',
        downloadUrl: '#',
      },
      {
        id: '6',
        title: 'EE.08 2021 czerwiec',
        description: 'Egzamin praktyczny EE.08',
        year: 2021,
        session: 'Summer',
        category: 'EE 0.8',
        downloadUrl: '#',
      },
      {
        id: '7',
        title: 'EE.08 2021 styczeń',
        description: 'Egzamin praktyczny EE.08',
        year: 2021,
        session: 'Winter',
        category: 'EE 0.8',
        downloadUrl: '#',
      },
      {
        id: '8',
        title: 'EE.08 2022 czerwiec',
        description: 'Egzamin praktyczny EE.08',
        year: 2022,
        session: 'Summer',
        category: 'EE 0.8',
        downloadUrl: '#',
      },
      {
        id: '9',
        title: 'EE.08 2022 styczeń',
        description: 'Egzamin praktyczny EE.08',
        year: 2022,
        session: 'Winter',
        category: 'EE 0.8',
        downloadUrl: '#',
      },
      {
        id: '10',
        title: 'EE.08 2023 czerwiec',
        description: 'Egzamin praktyczny EE.08',
        year: 2023,
        session: 'Summer',
        category: 'EE 0.8',
        downloadUrl: '#',
      },
      {
        id: '11',
        title: 'EE.08 2023 styczeń',
        description: 'Egzamin praktyczny EE.08',
        year: 2023,
        session: 'Winter',
        category: 'EE 0.8',
        downloadUrl: '#',
      },
      {
        id: '12',
        title: 'EE.08 2024 czerwiec',
        description: 'Egzamin praktyczny EE.08',
        year: 2024,
        session: 'Summer',
        category: 'EE 0.8',
        downloadUrl: '#',
      },
      {
        id: '13',
        title: 'EE.08 2024 styczeń',
        description: 'Egzamin praktyczny EE.08',
        year: 2024,
        session: 'Winter',
        category: 'EE 0.8',
        downloadUrl: '#',
      },
      {
        id: '14',
        title: 'EE.09 2019 czerwiec',
        description: 'Egzamin praktyczny EE.09',
        year: 2019,
        session: 'Summer',
        category: 'EE 0.9',
        downloadUrl: '#',
      },
      {
        id: '15',
        title: 'EE.09 2020 czerwiec',
        description: 'Egzamin praktyczny EE.09',
        year: 2020,
        session: 'Summer',
        category: 'EE 0.9',
        downloadUrl: '#',
      },
      {
        id: '16',
        title: 'EE.09 2020 styczeń',
        description: 'Egzamin praktyczny EE.09',
        year: 2020,
        session: 'Winter',
        category: 'EE 0.9',
        downloadUrl: '#',
      },
      {
        id: '17',
        title: 'EE.09 2021 czerwiec',
        description: 'Egzamin praktyczny EE.09',
        year: 2021,
        session: 'Summer',
        category: 'EE 0.9',
        downloadUrl: '#',
      },
      {
        id: '18',
        title: 'EE.09 2021 styczeń',
        description: 'Egzamin praktyczny EE.09',
        year: 2021,
        session: 'Winter',
        category: 'EE 0.9',
        downloadUrl: '#',
      },
      {
        id: '19',
        title: 'EE.09 2022 czerwiec',
        description: 'Egzamin praktyczny EE.09',
        year: 2022,
        session: 'Summer',
        category: 'EE 0.9',
        downloadUrl: '#',
      },
      {
        id: '20',
        title: 'EE.09 2022 styczeń',
        description: 'Egzamin praktyczny EE.09',
        year: 2022,
        session: 'Winter',
        category: 'EE 0.9',
        downloadUrl: '#',
      },
      {
        id: '21',
        title: 'EE.09 2023 czerwiec',
        description: 'Egzamin praktyczny EE.09',
        year: 2023,
        session: 'Summer',
        category: 'EE 0.9',
        downloadUrl: '#',
      },
      {
        id: '22',
        title: 'EE.09 2023 styczeń',
        description: 'Egzamin praktyczny EE.09',
        year: 2023,
        session: 'Winter',
        category: 'EE 0.9',
        downloadUrl: '#',
      },
      {
        id: '23',
        title: 'EE.09 2024 czerwiec',
        description: 'Egzamin praktyczny EE.09',
        year: 2024,
        session: 'Summer',
        category: 'EE 0.9',
        downloadUrl: '#',
      },
      {
        id: '24',
        title: 'EE.09 2024 styczeń',
        description: 'Egzamin praktyczny EE.09',
        year: 2024,
        session: 'Winter',
        category: 'EE 0.9',
        downloadUrl: '#',
      },
      {
        id: '25',
        title: 'INF.02 2021 czerwiec',
        description: 'Egzamin praktyczny INF.02',
        year: 2021,
        session: 'Summer',
        category: 'INF 02',
        downloadUrl: '/exams/INF02-2021-summer.pdf',
      },
      {
        id: '26',
        title: 'INF.02 2022 styczeń',
        description: 'Egzamin praktyczny INF.02',
        year: 2022,
        session: 'Winter',
        category: 'INF 02',
        downloadUrl: '/exams/INF02-2022-winter.pdf',
      },
      {
        id: '27',
        title: 'INF.02 2022 czerwiec',
        description: 'Egzamin praktyczny INF.02',
        year: 2022,
        session: 'Summer',
        category: 'INF 02',
        downloadUrl: '/exams/INF02-2022-summer.pdf',
      },
      {
        id: '28',
        title: 'INF.02 2023 styczeń',
        description: 'Egzamin praktyczny INF.02',
        year: 2023,
        session: 'Winter',
        category: 'INF 02',
        downloadUrl: '/exams/INF02-2023-winter.pdf',
      },
      {
        id: '29',
        title: 'INF.02 2023 czerwiec',
        description: 'Egzamin praktyczny INF.02',
        year: 2023,
        session: 'Summer',
        category: 'INF 02',
        downloadUrl: '/exams/INF02-2023-summer.pdf',
      },
      {
        id: '30',
        title: 'INF.02 2024 styczeń',
        description: 'Egzamin praktyczny INF.02',
        year: 2024,
        session: 'Winter',
        category: 'INF 02',
        downloadUrl: '/exams/INF02-2024-winter.pdf',
      },
      {
        id: '31',
        title: 'INF.02 2024 czerwiec',
        description: 'Egzamin praktyczny INF.02',
        year: 2024,
        session: 'Summer',
        category: 'INF 02',
        downloadUrl: '/exams/INF02-2024-summer.pdf',
      },
      {
        id: '32',
        title: 'Brak arkuszy :(',
        description: 'Brak dostępnych arkuszy',
        year: 2024,
        session: 'Summer',
        category: 'INF 03',
        downloadUrl: '/',
      },
    ];